### PR TITLE
Video call when near by

### PR DESCRIPTION
**Pull request by ChrisZhangProdigy**
I have changed the video call logic. The video will not open when the game is loaded. It will start video for the current user when user join the room. When two users get close to each other. It will start video chat. 

I did some test and it works well for two players. It is pretty buggy when three players are involved. I always saw socket disconnect issue. Maybe, it is too heavy to communicate socket event and webRTC call among multiple players?

### CODE REVIEW

**Comment by Lawton** [comment]
Maybe we want a toggle to turn this on and off for the demo since it's a little unstable

**Review by Lawton — APPROVED** [review]

**Comment by angieology** [comment]
yeah i'm not sure about merging it maybe we can keep a separate branch and see how far we get

**Comment by ChrisZhangProdigy** [comment]
Yes, let's leave this in a branch. I didn't figure out why it causes socket disconnect...

**Comment by angieology** [comment]
I fixed the issue of extra videos showing on my other branch. looks like we only need to emit one socket event. weird that you already have this (only emit once on server per call) 
I still can't get disconnect to work. The peers[peerId].close() does not seem to be triggering "close" event properly

**Pull request closed without merging**
